"""Add profile Pic

Revision ID: 6eb5a7974237
Revises: 7753d7853439
Create Date: 2023-07-21 00:05:54.882976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb5a7974237'
down_revision = '7753d7853439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenshot', schema=None) as batch_op:
        batch_op.alter_column('path',
               existing_type=sa.VARCHAR(length=640),
               type_=sa.String(length=255),
               nullable=True)

    with op.batch_alter_table('using', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('using', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    with op.batch_alter_table('screenshot', schema=None) as batch_op:
        batch_op.alter_column('path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=640),
               nullable=False)

    # ### end Alembic commands ###
